### ISSUE TITLE
Save ESI app between server executions

### ISSUE THREAD

**Issue by mcgibbon** [wgilpin/recruitment-ascee#21]
The way we load the ESI app currently gives room for error when restarting sessions too often, or if the swagger app is down. I should refactor the backend so that we save the app data in some way that can be reused between sessions.

For example:

```
the runtime process for the instance running on port 18199 has unexpectedly quit

[2019-01-30 14:16:08 -0800] [14948] [INFO] Starting gunicorn 19.9.0
[2019-01-30 14:16:08 -0800] [14948] [INFO] Listening at: http://0.0.0.0:18199 (14948)
[2019-01-30 14:16:08 -0800] [14948] [INFO] Using worker: sync
[2019-01-30 14:16:08 -0800] [14951] [INFO] Booting worker with pid: 14951
[2019-01-30 14:16:10 -0800] [14951] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/tmp/tmp_wfdT1/lib/python3.7/site-packages/gunicorn/arbiter.py", line 583, in spawn_worker
    worker.init_process()
  File "/tmp/tmp_wfdT1/lib/python3.7/site-packages/gunicorn/workers/base.py", line 129, in init_process
    self.load_wsgi()
  File "/tmp/tmp_wfdT1/lib/python3.7/site-packages/gunicorn/workers/base.py", line 138, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/tmp/tmp_wfdT1/lib/python3.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/tmp/tmp_wfdT1/lib/python3.7/site-packages/gunicorn/app/wsgiapp.py", line 52, in load
    return self.load_wsgiapp()
  File "/tmp/tmp_wfdT1/lib/python3.7/site-packages/gunicorn/app/wsgiapp.py", line 41, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/tmp/tmp_wfdT1/lib/python3.7/site-packages/gunicorn/util.py", line 350, in import_app
    __import__(module)
  File "/home/twine/python/recruitment-ascee/server/main.py", line 21, in <module>
    from character_data import (
  File "/home/twine/python/recruitment-ascee/server/character_data.py", line 1, in <module>
    from esi import get_op, get_paged_op
  File "/home/twine/python/recruitment-ascee/server/esi.py", line 1, in <module>
    from database import get_op, get_paged_op
  File "/home/twine/python/recruitment-ascee/server/database.py", line 353, in <module>
    esi_app = App.create('https://esi.evetech.net/latest/swagger.json')
  File "/tmp/tmp_wfdT1/lib/python3.7/site-packages/pyswagger/core.py", line 364, in create
    app = kls.load(url)
  File "/tmp/tmp_wfdT1/lib/python3.7/site-packages/pyswagger/core.py", line 285, in load
    app.__raw, app.__version = app.load_obj(url, getter=getter, parser=parser)
  File "/tmp/tmp_wfdT1/lib/python3.7/site-packages/pyswagger/core.py", line 166, in load_obj
    obj = self.__resolver.resolve(jref, getter)
  File "/tmp/tmp_wfdT1/lib/python3.7/site-packages/pyswagger/resolve.py", line 62, in resolve
    obj = six.advance_iterator(getter)
  File "/tmp/tmp_wfdT1/lib/python3.7/site-packages/pyswagger/getter.py", line 32, in __next__
    obj = self.load(self.urls.pop(0))
  File "/tmp/tmp_wfdT1/lib/python3.7/site-packages/pyswagger/getter.py", line 138, in load
    return self.__simple_getter_callback__.__func__(path)
  File "/tmp/tmp_wfdT1/lib/python3.7/site-packages/pyswagger/getter.py", line 144, in _url_load
    f = six.moves.urllib.request.urlopen(path)
  File "/home/twine/anaconda3/envs/env3/lib/python3.7/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/home/twine/anaconda3/envs/env3/lib/python3.7/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/home/twine/anaconda3/envs/env3/lib/python3.7/urllib/request.py", line 641, in http_response
    'http', request, response, code, msg, hdrs)
  File "/home/twine/anaconda3/envs/env3/lib/python3.7/urllib/request.py", line 569, in error
    return self._call_chain(*args)
  File "/home/twine/anaconda3/envs/env3/lib/python3.7/urllib/request.py", line 503, in _call_chain
    result = func(*args)
  File "/home/twine/anaconda3/envs/env3/lib/python3.7/urllib/request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 500: Internal Server Error
[2019-01-30 14:16:10 -0800] [14951] [INFO] Worker exiting (pid: 14951)
[2019-01-30 14:16:10 -0800] [14948] [INFO] Shutting down: Master
[2019-01-30 14:16:10 -0800] [14948] [INFO] Reason: Worker failed to boot.
```

**Comment by wgilpin** [comment]
Ah great I wondered what this error was

**Comment by mcgibbon** [comment]
Implemented now, we'll just have to watch out that the implementation works when deployed (since it saves a file, and not all hosts like that).
